spring.application.name=CodeMigraton
spring.datasource.url=jdbc:postgresql://localhost:5432/codemigraton
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=sandhani@0209
spring.jpa.hibernate.ddl-auto=update
app.name=CodeMigraton
app.version=1.0 
spring.profiles.active = dev  
app.owner = ${APP_OWNER:Sandhani}
server.port=8080

